### ISSUE TITLE
[nginx] 404 on .fleek websocket Upgrade attempt, using proxy_pass

### ISSUE THREAD

**Issue by qq99** [Shopify/fleek#1]
:heart: :heart: :heart: this gem!!

Here's a minimal nginx configuration:

```nginx
http {

  upstream unicorns {
    server 127.0.0.1:3000;
  }

  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;

  include /etc/nginx/mime.types;
  index index.html index.htm index.php;

  default_type application/octet-stream;

  server {
    listen 8080;
    listen [::]:8080 default ipv6only=on;

    root /some/path/to/public;
    index index.html index.htm;

    server_name your.hostname localhost;

    location / {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_pass http://unicorns;
    }
}
```

Tried to pare it down from [this nginx conf](https://github.com/qq99/muvee/blob/master/muvee.nginx.conf.erb); this is the only location directive that should be affecting things.

So rails runs on 3000, nginx on 8080.

- If I visit `your.hostname:8080`, the `.fleek` websocket upgrade fails with 404 Not Found
- If I visit `localhost:3000`, the `.fleek` websocket upgrade works with 101 Switching Protocols

In my app, I was previously using Tubesock::Hijack so it seems to me that it should still be possible to proxy_pass web sockets

I will also note I can run tubesock & fleek at same time if I use `localhost:3000`, whereas only tubesock works on `your.hostname:8080`

Thanks again, @bouk !

**Comment by qq99** [comment]
404/nginx case:

```
Started GET "/fleek-asset-update-connection" for 127.0.0.1 at 2016-03-04 20:56:34 -0500
Started GET "/fleek-asset-update-connection/"[non-WebSocket] for 127.0.0.1 at 2016-03-04 20:56:34 -0500
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: close, HTTP_UPGRADE: )
Finished "/fleek-asset-update-connection/"[non-WebSocket] for 127.0.0.1 at 2016-03-04 20:56:34 -0500
```

vs

```
Started GET "/fleek-asset-update-connection" for 127.0.0.1 at 2016-03-04 20:57:36 -0500
Started GET "/fleek-asset-update-connection/" [WebSocket] for 127.0.0.1 at 2016-03-04 20:57:36 -0500
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
```

**Comment by bouk** [comment]
could you walk through https://www.nginx.com/blog/websocket-nginx/ and see if it needs an update to the Nginx config?

**Comment by qq99** [comment]
Confirmed that if I add:

```
    location /.fleek-connection {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_pass http://unicorns;
    }
```

it works!  No idea why/how Tubesock doesn't need this, but I can work with this :)
